[package]
name = "hello_world_in_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo = "0.11.0"
serde = "1.0.217"
serde_json = "1.0.136"
stylist = { version = "0.13.0", features = ["yew"] }
yew =  { version =  "0.21.0", features = ["csr"] }
